FROM debian:buster

RUN apt-get update \
&& apt-get install -y software-properties-common bc unzip curl wget \
&& rm -rf /var/lib/apt/lists/*

COPY package-bdd.zip /home/depotbdd/

RUN cd /home/depotbdd/ \
&& unzip package-bdd.zip \
&& chmod +x install.sh
#&& ./install.sh