version: '3.8'
services:
  imgprdapp:
    build: 
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    privileged: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - imgprdapp:/data

volumes:
  imgprdapp: