---
- name: Evolucare Déploiment ITImaging
  hosts: all
  gather_facts: no
  vars:
    VMClient: "Evolucare interne"
    VMName: "VM-IMGPRD-HUB"
    VMPath: "N:\\HYPERV\\"
    VMCpu: "2"
    SwitchInterne: "vSwitch Interne"
    URLHUB: "https://downloads-imaging.evolucare.com/masters/IMGPRD-HUBv3_master/IMGPRD-HUB_MASTER_HV.zip"
    DiskDestination: "{{ VMPath }}{{ VMName }}\\Virtual Hard Disks\\IMGPRD-HUB_MASTER_HV.zip"
    DiskPath: "{{ VMPath }}{{ VMName }}\\Virtual Hard Disks\\"
    UserName: "a.lenglet"
    UserPassword: "Armand@3279!"
    Cred: New-Object System.Management.Automation.PSCredential ("{{ UserName }}{{ UserPassword }}")
        
  tasks:

    - name: Création des vSwitch Interne
      ansible.windows.win_shell: |
        New-VMSwitch -Name "{{ SwitchInterne }}" -SwitchType Internal -Notes "For Evolucare Imaging Internal VMs"
        New-NetIPAddress -IPAddress 10.42.42.1 -InterfaceAlias "vEthernet ({{ SwitchInterne }})"
        Disable-NetAdapterBinding -InterfaceAlias "vEthernet ({{ SwitchInterne }})" -ComponentID ms_tcpip6
      register: create_network_vswitch

    - name: Check vérification
      debug:
          var: create_network_vswitch.stdout

    - name: Créer la machine virtuelle {{ VMName }}
      ansible.windows.win_shell: |
        New-VM -Name "{{ VMName }}" -MemoryStartupBytes 2147483648 -Generation 1 -SwitchName "{{ SwitchInterne }}" -Path "{{ VMPath }}"
        Set-VM -Name "{{ VMName }}" -ProcessorCount "{{ VMCpu }}"
        New-Item "{{ DiskPath }}" -ItemType Directory
      register: vm_creation_output

    - name: Check vérification
      debug:
          var: vm_creation_output.stdout

    - name: Téléchargement du Master {{ VMName }}
      ansible.windows.win_get_url:
        url: "{{ URLHUB }}"
        dest: "{{ DiskDestination }}"
        url_username: "{{ UserName }}"
        url_password: "{{ UserPassword }}"
  
    - name: Conversion vHDX et Intégration
      ansible.windows.win_shell: |      
        Expand-Archive -LiteralPath "{{ DiskDestination }}" -DestinationPath "{{ DiskPath }}" -Force
        Convert-VHD -Path "{{ DiskPath }}MASTER-IMGPRD-HUB-disk1.vhd" -DestinationPath "{{ DiskPath }}{{ VMName }}-disk1-fixe.vhdx" -VHDType Fixed
        Convert-VHD -Path "{{ DiskPath }}MASTER-IMGPRD-HUB-disk2.vhd" -DestinationPath "{{ DiskPath }}{{ VMName }}-disk2-fixe.vhdx" -VHDType Fixed
        Add-VMHardDiskDrive -VMName "{{ VMName }}" -Path "{{ DiskPath }}{{ VMName }}-disk1-fixe.vhdx"
        Add-VMHardDiskDrive -ControllerType SCSI -VMName "{{ VMName }}" -Path "{{ DiskPath }}{{ VMName }}-disk2-fixe.vhdx"
      register: add_convert_disk

    - name: Check vérification
      debug:
          var: add_convert_disk.stdout
       
    - name: Nettoyage des disques et répertoire
      ansible.windows.win_shell: |
        rm "{{ DiskPath }}\IMGPRD-HUB_MASTER_HV.zip" -Force
        rm "{{ DiskPath }}\*.vhd" -Force
      register: remove_files

    - name: Check vérification
      debug:
          var: remove_files.stdout

    - name: Envoi les informations sous Webhook
      uri:
        url: "https://evolucare.webhook.office.com/webhookb2/b9030cb5-bc6f-47a7-bd33-9375b84c8c37@2b4b3e6a-d583-4961-985c-560a2bb0df3d/IncomingWebhook/0c84d034a0d6446baec23eac224b0288/5a806b24-ccd0-463d-9a8c-a098c09c50b5"      
        body: "{{ VMClient }} / {{ VMName }} --> Ok"
        body_format: json
        method: POST
      register: webhook_result

    - name: Check vérification
      debug:
          var: webhook_result.stdout

    - name: Démarrer la VM nouvellement créée
      ansible.windows.win_shell: |
        Start-VM -Name "{{ VMName }}"